#!/bin/bash

# Get backup directory
if [ -z "$1" ]; then
  backup_dir=.
else
  backup_dir="$1"
fi

# Get timestamp
if [ -z "$2" ]; then
  timestamp=$(date -u "+%Y%m%d%H%M%S")
else
  timestamp="$2"
fi

# Back up /etc/gitlab configuration
filename="$backup_dir/etc_gitlab_${timestamp}.tar.bz2"
tar cjf $filename -C / etc/gitlab
echo "$filename"
