#!/bin/bash

# Get timestamp
if [ -z "$1" ]; then
  timestamp=$(date -u "+%Y%m%d%H%M%S")
else
  timestamp="$1"
fi

# Create backup
filename="$(pwd)/etc_nginx_${timestamp}.tar.bz2"
tar cjf $filename -C / etc/nginx

# Handle errors and return filename upon success
returncode=$?
if [ $returncode -ne 0 ]; then
  echo "error: could not create backup" >&2
  exit 1
else
  echo "$filename"
fi
